version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bookmark-backend
    expose:
      - "6005"
    env_file:
      - ./backend/.env.prod
    networks:
      - bookmark-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookmark-frontend
    expose:
      - "3002"
    env_file:
      - ./frontend/.env.prod
    depends_on:
      - backend
    networks:
      - bookmark-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: bookmark-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf.template:/etc/nginx/templates/default.conf.template
      #- ./nginx/nginx.initial.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # SSL certificates
      - ./certbot/www:/var/www/certbot:ro  # For Let's Encrypt challenges
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - backend
      - frontend
    networks:
      - bookmark-network
    restart: unless-stopped

  # Auto-renew SSL certificates
  certbot:
    image: certbot/certbot
    container_name: bookmark-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${SSL_EMAIL}
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

networks:
  bookmark-network:
    driver: bridge
